"""Initial migration.

Revision ID: 888c61b53d05
Revises: 6012fe8de495
Create Date: 2021-08-24 22:33:13.130779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '888c61b53d05'
down_revision = '6012fe8de495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kdfd_challenge_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('kdfd_data', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kdfd_challenge_model')
    # ### end Alembic commands ###
